= PackageURL (PURL) Basic

A very basic library for working with PackageURL / PURL (Kotlin Multiplatform).

[WARNING,caption="Check the official libraries before using this!"]
====
Before using this library, please ensure you check the libraries created by the original PackageURL team here: https://github.com/package-url.

*This library is designed to provide only basic functionality, utilizing a slightly different implementation of the standard than that of the original authors*.
While we strive to follow the specification to the letter, we do fail multiple tests on https://github.com/package-url/purl-spec/blob/main/test-suite-data.json[the original PURL test suite] due to respectfully disagreeing with their vision of how the specification should be implemented.
====

== Deviations from the specification and the reasons for failing the original PURL specification tests

The goal of this implementation is to simply parse/create a PURL and let the downstream system handle the rest in the simplest form possible.
So:

. We refuse to maintain special implementations for any "known" items such as "known package types" or "known qualifiers", etc.
. Therefore, we don't support any special cases for known package types such as Maven, Docker, PyPI, etc.
. The most notable consequence is that our canonical purls are always lowercase, which fails the majority of case-sensitive special case purl examples
. And we still encode all qualifier values (so no special treatment for `checksum`, `vers`, `repository_url`, `download_url`, `vcs_url`, etc.)

== Supported platforms

Currently only supports JVM and JS platforms.

== Using the library

[source,kotlin]
----
dependencies {
    implementation("dev.samoylenko:packageurl-basic:0.1.0")
}
----
