= PackageURL (PURL) Basic

A very basic library for parsing PackageURL / PURL (Kotlin Multiplatform).

[WARNING]
====
⚠️ *This implementation fails the PURL specification https://github.com/package-url/purl-spec/blob/main/docs/tests.md[test suite]* ⚠️

Before using this library, please ensure you check the libraries created by the original PackageURL team here: https://github.com/package-url.
====

== Deviations from the specification

The goal of this implementation is to simply parse/create a PURL and let the downstream system handle the rest in the simplest form possible.
So:

. We do not maintain special implementations for any "known" items such as "known package types" or "known qualifiers", etc.
. Therefore, we don't support any special cases for known package types such as Maven, Docker, PyPI, etc.
. And we still encode all qualifier values (so no special treatment for `checksum`, `vers`, `repository_url`, `download_url`, `vcs_url`, etc.)

== Supported platforms

Currently only supports JVM and JS platforms.

== Using the library

[source,kotlin]
----
dependencies {
    implementation("dev.samoylenko:packageurl-basic:0.2.0")
}
----
